fix(nextcloud): fix traefik redirect regex ingress type (#37708)
**Description**
The current ingress type for traefik of nextcloud is wrong. It has to be
"redirect-regex" instead of "redirectRegex".

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [x] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] 🔃 Refactor of current code
- [ ] 📜 Documentation Changes

**🧪 How Has This Been Tested?**
I experimented with nextcloud, otherwise error is
```
Error: execution error at (nextcloud/templates/common.yaml:92:4): Traefik - Middleware [redirectRegex] is not supported. Supported middlewares are [compress, plugin-real-ip, plugin-rewrite-response-headers, rate-limit, replace-path, replace-path-regex, retry, strip-prefix-regex, chain, content-type, plugin-mod-security, plugin-theme-park, redirect-regex, basic-auth, buffering, forward-auth, headers, ip-allow-list, plugin-bouncer, plugin-geoblock, redirect-scheme, add-prefix, strip-prefix]
helm.go:86: 2025-07-23 21:29:35.832733916 +0200 CEST m=+0.440218084 [debug] execution error at (nextcloud/templates/common.yaml:92:4): Traefik - Middleware [redirectRegex] is not supported. Supported middlewares are [compress, plugin-real-ip, plugin-rewrite-response-headers, rate-limit, replace-path, replace-path-regex, retry, strip-prefix-regex, chain, content-type, plugin-mod-security, plugin-theme-park, redirect-regex, basic-auth, buffering, forward-auth, headers, ip-allow-list, plugin-bouncer, plugin-geoblock, redirect-scheme, add-prefix, strip-prefix]
```

**📃 Notes:**
<!-- Please enter any other relevant information here -->

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand
areas
- [ ] 📄 I have made changes to the documentation
- [ ] 🧪 I have added tests to this description that prove my fix is
effective or that my feature works
- [x] ⬆️ I increased versions for any altered app according to semantic
versioning
- [x] I made sure the title starts with `feat(chart-name):`,
`fix(chart-name):`, `chore(chart-name):`, `docs(chart-name):` or
`fix(docs):`

**➕ App addition**

If this PR is an app addition please make sure you have done the
following.

- [ ] 🖼️ I have added an icon in the Chart's root directory called
`icon.png`

---

_Please don't blindly check all the boxes. Read them and only check
those that apply.
Those checkboxes are there for the reviewer to see what is this all
about and
the status of this PR with a quick glance._

---------

Signed-off-by: Alfred Göppel <43101280+alfi0812@users.noreply.github.com>
Co-authored-by: Alfred Göppel <43101280+alfi0812@users.noreply.github.com>